### ISSUE TITLE
Allow muliple API Host for icingaweb2::module::monitoring

### ISSUE THREAD

**Issue by baurmatt** [Icinga/puppet-icingaweb2#155]
## Expected Behavior
It should be possible to define multiple API hosts 

## Current Behavior
You can only specify one `api_host` which isn't enough in a HA setup. Also you can't specify a command pipe transport.

## Possible Solution
Implement parameter `commandtransports` which is a hash which also allows to specify the type. For example:

```
commandtransports:
  'master01':
    type: 'api'
    host: '10.1.1.1'
    port: 5665
    username: 'web'
    password: 'foo'
  'master02':
    type: 'api'
    host: '10.1.1.2'
    port: 5665
    username: 'web'
    password: 'foo'
```

## Steps to Reproduce (for bugs)
Search for a option to specify muliple api_hosts

## Context
In a HA setup: If `api_host` isn't reachable you can't send commands.

## Your Environment

* Module version (`puppet module list`): 29cbce145d6b255752674bb76fe866e9bfceea86
* Puppet version (`puppet -V`): 4.10.1
* Operating System and version: Ubuntu 16.04.2
